stages:
  - commit-build
  - full-build

#--------------------------------------------------------------------
# Templates
#--------------------------------------------------------------------

#**************************************
# Build types
#**************************************

### Commit build
.job_template: &commit_build_def
  stage: commit-build
  except:
      - triggers
      - tags

### Full build
.job_template: &full_build_def
  stage: full-build
  only:
    - triggers
    - tags

#**************************************
# Platforms
#**************************************

### OSX
.job_template: &osx_def
  allow_failure: true
  tags:
    - osx

### Archlinux
.job_template: &archlinux_def
  image: pritunl/archlinux
  tags:
    - linux
  before_script:
    - ./scripts/env-setup/linux/archlinux-env-setup.sh
    - export DISPLAY=:99
    - Xvfb :99 -ac &

### Ubuntu 16.04
.job_template: &ubuntu_def
  image: ubuntu:latest
  tags:
    - linux
  before_script:
    - ./scripts/env-setup/linux/ubuntu-16.04-env-setup.sh
  variables:
    CMAKE_PREFIX_PATH: "/opt/qt57"

### Fedora
.job_template: &fedora_def
  image: fedora:latest
  tags:
    - linux
  before_script:
    - ./scripts/env-setup/linux/fedora-env-setup.sh

#--------------------------------------------------------------------
# Commit Build
#--------------------------------------------------------------------
commit-build:linux:
  <<: *commit_build_def
  <<: *archlinux_def
  script:
    - ./scripts/build/linux/build.sh --release --coverage
    - ./scripts/build/linux/runtests.sh --release

coverage:
  <<: *commit_build_def
  <<: *archlinux_def
  script:
    - ./scripts/build/linux/build.sh --debug --coverage
    - ./scripts/build/linux/runtests.sh --debug --coverage
  artifacts:
    name: "coverage"
    paths:
      - cmake-build-debug/coverage/

#--------------------------------------------------------------------
# Full Build
#--------------------------------------------------------------------
# todo
