stages:
  - commit-build
  - full-build

#--------------------------------------------------------------------
# Templates
#--------------------------------------------------------------------

#**************************************
# Build types
#**************************************

### Commit build
.job_template: &commit_build_def
  stage: commit-build
  except:
      - triggers
      - tags

### Full build
.job_template: &full_build_def
  stage: full-build
  only:
    - triggers
    - tags

#**************************************
# Platforms
#**************************************

### Windows
.job_template: &windows_def
  allow_failure: true
  tags:
    - windows
  before_script:
    - chmod +x ./scripts/build/windows/build.bat
    - chmod +x ./scripts/build/windows/runtests.bat

### OSX
.job_template: &osx_def
  allow_failure: true
  tags:
    - osx

### Archlinux
.job_template: &archlinux_def
  image: pritunl/archlinux
  tags:
    - linux
  before_script:
    - ./scripts/env-setup/linux/archlinux-env-setup.sh
    - export DISPLAY=:99.0

### Ubuntu 16.04
.job_template: &ubuntu_def
  image: ubuntu:latest
  tags:
    - linux
  before_script:
    - ./scripts/env-setup/linux/ubuntu-env-setup.sh
  variables:
    CMAKE_PREFIX_PATH: "/opt/qt57"

### Fedora
.job_template: &fedora_def
  image: fedora:latest
  tags:
    - linux
  before_script:
    - ./scripts/env-setup/linux/fedora-env-setup.sh

#--------------------------------------------------------------------
# Commit Build
#--------------------------------------------------------------------
commit-build:archlinux:
  <<: *commit_build_def
  <<: *archlinux_def
  script:
    - ./scripts/build/linux/build.sh --debug --coverage
    - ./cmake-build-debug/tests/MellowPlayer.Tests
  artifacts:
    name: "CoverageReport_${CI_BUILD_NAME}_${CI_BUILD_REF_NAME}"
    paths:
      - cmake-build-debug/coverage

commit-build:windows:
  <<: *commit_build_def
  <<: *windows_def
  script:
    - cd scripts/build/windows
    - ./build.bat
    - ./runtests.bat

commit-build:osx:
  <<: *commit_build_def
  <<: *osx_def
  script:
    - ./scripts/build/osx/build.sh --debug
    - ./scripts/build/osx/runtests.sh --debug

#--------------------------------------------------------------------
# Full Build
#--------------------------------------------------------------------
# todo
