language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: require
      dist: trusty
    - os: osx
      compiler: clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

install: source ./scripts/travis/install.sh
before_script: source ./scripts/travis/before_script.sh
script: ./scripts/travis/script.sh
