language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      sudo: require
      dist: trusty
    - os: osx
      compiler: clang

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5
            - gcc-5

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        sudo ./scripts/env-setup/linux/ubuntu-14.04-env-setup.sh;
        source /opt/qt*/bin/qt*-env.sh;
        export CXX="g++-5" CC="gcc-5";
      fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        ./scripts/env-setup/osx/env-setup.sh;
      fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./scripts/build/linux/build.sh --release;
      ./scripts/build/linux/runtests.sh --release;
    fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./scripts/build/osx/build.sh --release;
      ./scripts/build/osx/runtests.sh --release;
    fi

after_success:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo pip install cpp-coveralls;
      ./scripts/build/linux/build.sh --debug --coverage;
      ./scripts/build/linux/runtests.sh --debug;
      coveralls --exclude /opt --exclude /usr  --exclude tests/ --exclude 3rdparty -E '.*qrc_.*' -E '.*moc_.*'  -E '.*cmake-build-.*' -b 'cmake-build-debug' -r '.';
    fi
