version: "3.3.50.{build}"
os: Visual Studio 2017
platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: wg7W1ZZ7YFwdtZOJ6lhEgTzHuHuELoE0Zu+FjVliK0LBi24TUq6zSfYLuhtrVMsn

configuration:
  - Release

clone_folder: C:\projects\MellowPlayer

branches:
  except:
    - gh-pages
    
install:
    - choco install -y qbs --version 1.11.0

build_script:
  - cd C:\projects\MellowPlayer\scripts\appveyor
  - init.bat
  - build.bat
  - cd C:\projects\MellowPlayer\scripts\packaging\windows
  - make_installer.bat

test_script:
  - cd C:\projects\MellowPlayer\scripts\appveyor
  - runtests.bat

deploy_script:
  - if defined APPVEYOR_REPO_TAG_NAME pip install github3.py
  - cd C:\projects\MellowPlayer
  - if defined APPVEYOR_REPO_TAG_NAME python scripts\upload.py %APPVEYOR_REPO_TAG_NAME% build/release/install-root/dist/*

artifacts:
  - path: build\release\install-root\dist\MellowPlayer_Setup.exe
    name: MellowPlayer_Setup

# display remote desktop information and block build
#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
