version: "3.0.0.{build}"
os: Visual Studio 2015
platform:
  - x64

configuration:
  - Release

init:
  - cmake --version
  - msbuild /version

clone_folder: C:\projects\MellowPlayer

branches:
  except:
    - gh-pages

before_build:
  - cd scripts\env-setup\windows
  - env-setup.bat
  - cd scripts\build\windows

build_script:
  - build.bat

test_script:
  - cd ..\scripts\build\windows
  - runtests.bat

