version: "3.2.50.{build}"
os: Visual Studio 2015
platform:
  - x64

environment:
  GITHUB_TOKEN:
    secure: wg7W1ZZ7YFwdtZOJ6lhEgTzHuHuELoE0Zu+FjVliK0LBi24TUq6zSfYLuhtrVMsn

configuration:
  - Release

init:
  - cmake --version
  - msbuild /version

clone_folder: C:\projects\MellowPlayer

branches:
  except:
    - gh-pages

build_script:
  - cd C:\projects\MellowPlayer\scripts\appveyor
  - build.bat
  - cd C:\projects\MellowPlayer\scripts\packaging\windows
  - make_installer.bat
  - cd C:\projects\MellowPlayer

test_script:
  - cd C:\projects\MellowPlayer\scripts\appveyor
  - runtests.bat

deploy_script:
  - if defined APPVEYOR_REPO_TAG_NAME pip install github3.py
  - if defined APPVEYOR_REPO_TAG_NAME python scripts\upload.py %APPVEYOR_REPO_TAG_NAME% dist/*

artifacts:
  - path: C:\projects\MellowPlayer\dist\MellowPlayer_Setup.exe
    name: MellowPlayer_Setup

# display remote desktop information and block build
#on_failure:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
