version: "3.0.0.{build}"
os: Visual Studio 2015
platform:
  - x64

configuration:
  - Release

init:
  - cmake --version
  - msbuild /version

clone_folder: C:\projects\MellowPlayer

branches:
  except:
    - gh-pages

install:
  - choco install -y InnoSetup

build_script:
  - cd scripts\build\windows
  - build.bat

test_script:
  - cd C:\projects\MellowPlayer\scripts\build\windows
  - runtests.bat

on_success:
  - cd C:\projects\MellowPlayer\scripts\packaging\windows
  - make_installer.bat

artifacts:
  - path: dist/MellowPlayer_Setup.exe
    name: Windows Installer x64

