@startuml

namespace MellowPlayer.Main {
    class Program {
        + main(): int
        + onInitialized()
        + onStarted()

    }
    Program --> MellowPlayer.Infrastructure.IApplication
    Program --> MellowPlayer.Presentation.IContextProperties
    Program --> MellowPlayer.Presentation.IMainWindow
    Program --> MellowPlayer.Presentation.IMprisPlayer
    Program -up-> MellowPlayer.Domain.IPlayers
    Program --> MellowPlayer.Infrastructure.IUpdater
}

namespace MellowPlayer.Domain {
    interface IPlayers
}

namespace MellowPlayer.Infrastructure {
    interface IUpdater

    interface IApplication {
        initialized: signal<void>
        started: signal<bool>
        initialize()
        run()
        quit()
        restart()
    }

    class ApplicationDecorator {
        + initialized: signal<void>
        + started: signal<bool>
        # _application: IApplication
        + initialize()
        + run()
        + quit()
        + restart()
    }

    IApplication <|.. ApplicationDecorator

    class SingleInstance {
        + initialize()
        + run()
    }
    ApplicationDecorator <|-- SingleInstance

    class WithCommandLineArguments {
        + run()
    }
    ApplicationDecorator <|-- WithCommandLineArguments

    class WithLogging {

    }
    ApplicationDecorator <|-- WithLogging
}

namespace MellowPlayer.Presentation {
    interface IQtApplication {
    }
    class QtApplication {

    }
    IQtApplication <|-- QtApplication
    class Application {
        + quitRequested: signal<void>
        + requestQuit()
        --
        + register(IQmlApplicationEngine)
        --
        + initialize()
        + run()
        + quit()
        + restart()
    }
    MellowPlayer.Infrastructure.IApplication <|.. Application
    IContextProperty <|.. Application
    Application -down-> IQtApplication

    interface IQmlApplicationEngine {
        setContextProperty(QString, QObject*)
    }
    class QmlApplicationEngine {
        - _qQmlApplicationEngine: QQmlApplicationEngine
        +setContextProperty(QString, QObject*)
    }
    IQmlApplicationEngine <|.. QmlApplicationEngine

    interface IContextProperty {
        id: QString
        register(IQmlApplicationEngine)
    }

    class ContextProperty {
        + ContextProperty()
        + ContextProperty(IContextProperties)
        + {abstract} id: QString
        + {abstract} register(IQmlApplicationEngine)
    }
    IContextProperty <|.. ContextProperty
    ContextProperty .up.> IContextProperties

    interface IContextProperties {
        add(IContextProperty)
        initialize()
    }

    class ContextProperties {
        - items_: QList<IContextProperty*>
        + initialize()
        + add(IContextProperty)
    }
    IContextProperties <|.. ContextProperties
    ContextProperties --> IQmlApplicationEngine

    interface IMainWindow {
        show()
        hide()
        close()
    }

    class MainWindow {
        + id: QString
        + show()
        + hide()
        + close()
    }
    IMainWindow <|... MainWindow
    ContextProperty <|-- MainWindow

    interface IMprisPlayer {
        start()
    }
    class MprisPlayer {
        + start()
    }
    IMprisPlayer <|-- MprisPlayer

    class NullMprisPlayer {
        + start()
    }
    IMprisPlayer <|-- NullMprisPlayer

}


'note bottom
'
'int main(argc, argv) {
'    QApplication qtApp(argc, argv); // bound by instance in injector
'    // dependency injector setup
'    ...
'    auto applicationFactory = injector.create<IApplicationFactory>();
'    auto app = applicationFactory.create();
'    return app->run();
'}
'
'end note

@enduml
