@startuml

package MellowPlayer::Infrastructure {
    class StreamingServiceLoader {
        + load()
        - filters_: IPlatformFilters
    }
    StreamingServiceLoader -right-> IPlatformFilters: filters_

    interface IPlatformFilters {
        match(QString) bool
    }

    enum Filters {
        All,
        Linux,
        AppImage,
        OSX,
        Windows
    }

    class FilterConverter {
        QString toString(Filter);
        Filter fromString(filter);
    }

    class TokenizedFilters {
        - filters_: QList<Filter>
        + toString(): QString
        + begin(): QList<Filter>::const_iterator
        + end() : QList<Filter>::const_iterator
    }
    TokenizedFilters ..> FilterConverter: <<use>>

    interface IPlatformFilterFactory

    class PlatformFilterFactory {
        + Create(Filter filter): unique_ptr<IPlatformFilter>
    }
    IPlatformFilterFactory <|-- PlatformFilterFactory
    PlatformFilterFactory ..> IPlatformFilter: <<create>>

    class PlatformFilters {
        + match(QString): bool
        --
        - tokenizedFilter_: TokenizedFilters
        - filterFactory_: IPlatformFilterFactory
    }
    IPlatformFilters <|-- PlatformFilters
    PlatformFilters -left-> TokenizedFilters
    PlatformFilters -right-> IPlatformFilterFactory

    PlatformFilters .left.> IPlatformFilter: <<match>>

    interface IPlatformFilter {
         match(): bool
    }

    class AllFilter {
        + match(): bool
    }
    IPlatformFilter <|-- AllFilter
    note top
    Always return true
    end note

    class LinuxFilterBase {
        # isAppImage_
        + {abstract} match(): bool
    }
    IPlatformFilter <|-right- LinuxFilterBase

    class LinuxFilter {
        # isAppImage_
        + match(): bool
    }
    LinuxFilterBase <|-- LinuxFilter

    class AppImageFilter {
        # isAppImage_
        + match(): bool
    }
    LinuxFilterBase <|-- AppImageFilter

    class OsxFilter {
        - isOsx_: bool
        + match(): bool
    }
    IPlatformFilter <|-- OsxFilter

    class WindowsFilter  {
        - isWindows_: bool
        + match(): bool
    }
    IPlatformFilter <|-- WindowsFilter
}

@enduml