@startuml

namespace MellowPlayer.Application {

class ISettingsProvider

class UserScripts {
    - _items: QList<IUserScript*>
    + UserScripts(QString serviceName);
    + count() : int
    + at(int) : IUserScript*
    + toList() : QList<IUserScript*>
    + remove(QString)
    + add(IUserScript* userScript)
}
UserScripts "*" -> IUserScript
UserScripts "*" --> ISettingsProvider

interface IUserScript {
    path(): QString
    name(): QString
    setName(QString)
    code() : QString
    import(QString path)
    load(QString path)
}

class UserScriptBase {
    - name_: QString
    # path_: QString
    # code_: QString
    + path(): QString
    + name(): QString
    + setName(QString):
    + code(): QString
}

IUserScript <|-- UserScriptBase

class StreamingService {
    - _userScripts: UserScripts*
    + userScripts(): UserScripts*
}

StreamingService -right-> UserScripts

}

namespace MellowPlayer.Infrastructure {

class UserScript {
    + import(QString path)
    + load(QString path)
}

MellowPlayer.Application.UserScriptBase <|-- UserScript

}

namespace MellowPlayer.Presentation {
    class UserScriptsViewModel {
        - _userScripts: ListModel<UserScriptViewModel>
        + model(): ListModel<UserScriptViewModel>
        + addScript(QString path)
        + removeScript(QString name)
    }
    class UserScriptViewModel {
        - _userScript: IUserScript&
        + code(): QString
        + name(): QString
        + setName(QString)
        + path(): QString
    }

    class StreamingServiceViewModel {
        + userScripts(): UserScriptViewModel*
    }

    StreamingServiceViewModel -> UserScriptsViewModel
    StreamingServiceViewModel --> MellowPlayer.Application.StreamingService
    UserScriptsViewModel --> MellowPlayer.Application.UserScripts
    UserScriptViewModel --> MellowPlayer.Application.IUserScript
    UserScriptsViewModel "*" -> UserScriptViewModel
}

@enduml
