# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/renega_666/Documents/MellowPlayer/forms/main_window.ui'
#
# Created: Sun Nov  2 14:30:32 2014
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from mellowplayer.qt import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1207, 828)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/application-x-mellowplayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageHome)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.pageHome)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 6, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 10, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.pushButtonPreferences = QtWidgets.QPushButton(self.pageHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPreferences.sizePolicy().hasHeightForWidth())
        self.pushButtonPreferences.setSizePolicy(sizePolicy)
        self.pushButtonPreferences.setObjectName("pushButtonPreferences")
        self.gridLayout_3.addWidget(self.pushButtonPreferences, 1, 1, 1, 1)
        self.pushButtonQuit = QtWidgets.QPushButton(self.pageHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuit.sizePolicy().hasHeightForWidth())
        self.pushButtonQuit.setSizePolicy(sizePolicy)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.gridLayout_3.addWidget(self.pushButtonQuit, 2, 1, 1, 1)
        self.pushButtonSelect = QtWidgets.QPushButton(self.pageHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelect.sizePolicy().hasHeightForWidth())
        self.pushButtonSelect.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/edit-services.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonSelect.setIcon(icon1)
        self.pushButtonSelect.setObjectName("pushButtonSelect")
        self.gridLayout_3.addWidget(self.pushButtonSelect, 0, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageHome)
        self.pageWeb = QtWidgets.QWidget()
        self.pageWeb.setObjectName("pageWeb")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageWeb)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.webView = WebView(self.pageWeb)
        self.webView.setObjectName("webView")
        self.gridLayout_4.addWidget(self.webView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageWeb)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1207, 34))
        self.menubar.setObjectName("menubar")
        self.menuApplication = QtWidgets.QMenu(self.menubar)
        self.menuApplication.setObjectName("menuApplication")
        self.menuPlayback = QtWidgets.QMenu(self.menubar)
        self.menuPlayback.setObjectName("menuPlayback")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionSelect_service = QtWidgets.QAction(MainWindow)
        self.actionSelect_service.setObjectName("actionSelect_service")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPlayPause = QtWidgets.QAction(MainWindow)
        self.actionPlayPause.setObjectName("actionPlayPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setObjectName("actionPause")
        self.actionNext = QtWidgets.QAction(MainWindow)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionAbout_MellowPlayer = QtWidgets.QAction(MainWindow)
        self.actionAbout_MellowPlayer.setObjectName("actionAbout_MellowPlayer")
        self.actionReport_a_bug = QtWidgets.QAction(MainWindow)
        self.actionReport_a_bug.setObjectName("actionReport_a_bug")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuApplication.addAction(self.actionSelect_service)
        self.menuApplication.addAction(self.actionPreferences)
        self.menuApplication.addSeparator()
        self.menuApplication.addAction(self.actionQuit)
        self.menuPlayback.addAction(self.actionPlayPause)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addAction(self.actionNext)
        self.menuPlayback.addAction(self.actionPrevious)
        self.menu.addAction(self.actionAbout_MellowPlayer)
        self.menu.addSeparator()
        self.menu.addAction(self.actionReport_a_bug)
        self.menubar.addAction(self.menuApplication.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mellow Player"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/application-x-mellowplayer.png\"/></p><p align=\"center\"><span style=\" font-size:22pt; font-weight:600;\">Welcome to Mellow Player!</span></p><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">Please, select a cloud music service.</span></p><p align=\"center\"><br/></p></body></html>"))
        self.pushButtonPreferences.setText(_translate("MainWindow", "Preferences"))
        self.pushButtonQuit.setText(_translate("MainWindow", "Quit"))
        self.pushButtonSelect.setText(_translate("MainWindow", "Select cloud music service"))
        self.menuApplication.setTitle(_translate("MainWindow", "Application"))
        self.menuPlayback.setTitle(_translate("MainWindow", "Control"))
        self.menu.setTitle(_translate("MainWindow", "Help"))
        self.actionSelect_service.setText(_translate("MainWindow", "Select cloud music service"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPlayPause.setText(_translate("MainWindow", "Play/Pause"))
        self.actionPlayPause.setShortcut(_translate("MainWindow", "Media Play"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setShortcut(_translate("MainWindow", "Media Stop"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setShortcut(_translate("MainWindow", "Media Play"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionNext.setShortcut(_translate("MainWindow", "Media Next"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Media Previous"))
        self.actionAbout_MellowPlayer.setText(_translate("MainWindow", "About Mellow Player"))
        self.actionReport_a_bug.setText(_translate("MainWindow", "Report a bug"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))

from mellowplayer.gui.web import WebView
from . import icons_rc
