# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/Desktop/MellowPlayer/forms/main_window.ui'
#
# Created: Fri Oct 24 20:23:10 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/MellowPlayer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(6, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageHome = QtWidgets.QWidget()
        self.pageHome.setObjectName("pageHome")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.pageHome)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 5, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.pageHome)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 9, 1, 1, 1)
        self.pushButtonPreferences = QtWidgets.QPushButton(self.pageHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPreferences.sizePolicy().hasHeightForWidth())
        self.pushButtonPreferences.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/preferences-system.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPreferences.setIcon(icon1)
        self.pushButtonPreferences.setObjectName("pushButtonPreferences")
        self.gridLayout_2.addWidget(self.pushButtonPreferences, 3, 1, 1, 1)
        self.pushButtonLoad = QtWidgets.QPushButton(self.pageHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLoad.sizePolicy().hasHeightForWidth())
        self.pushButtonLoad.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/edit-services.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLoad.setIcon(icon2)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.gridLayout_2.addWidget(self.pushButtonLoad, 2, 1, 1, 1)
        self.pushButtonQuit = QtWidgets.QPushButton(self.pageHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuit.sizePolicy().hasHeightForWidth())
        self.pushButtonQuit.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme("exit")
        self.pushButtonQuit.setIcon(icon)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.gridLayout_2.addWidget(self.pushButtonQuit, 4, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageHome)
        self.pageWeb = QtWidgets.QWidget()
        self.pageWeb.setObjectName("pageWeb")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.pageWeb)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.webView = WebView(self.pageWeb)
        self.webView.setObjectName("webView")
        self.gridLayout_4.addWidget(self.webView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageWeb)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        self.menuApplication = QtWidgets.QMenu(self.menubar)
        self.menuApplication.setObjectName("menuApplication")
        self.menuPlayback = QtWidgets.QMenu(self.menubar)
        self.menuPlayback.setObjectName("menuPlayback")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionChoose_service = QtWidgets.QAction(MainWindow)
        self.actionChoose_service.setIcon(icon2)
        self.actionChoose_service.setObjectName("actionChoose_service")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setIcon(icon1)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/media-playback-start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon3)
        self.actionPlay.setObjectName("actionPlay")
        self.actionStop = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/media-playback-stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon4)
        self.actionStop.setObjectName("actionStop")
        self.actionPause = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/media-playback-pause.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon5)
        self.actionPause.setObjectName("actionPause")
        self.actionNext = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/go-next.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon6)
        self.actionNext.setObjectName("actionNext")
        self.actionPrevious = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/go-previous.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon7)
        self.actionPrevious.setObjectName("actionPrevious")
        self.actionAbout_MellowPlayer = QtWidgets.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/help-about.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_MellowPlayer.setIcon(icon8)
        self.actionAbout_MellowPlayer.setObjectName("actionAbout_MellowPlayer")
        self.actionReport_a_bug = QtWidgets.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/tools-report-bug.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport_a_bug.setIcon(icon9)
        self.actionReport_a_bug.setObjectName("actionReport_a_bug")
        self.menuApplication.addAction(self.actionChoose_service)
        self.menuApplication.addSeparator()
        self.menuApplication.addAction(self.actionPreferences)
        self.menuPlayback.addAction(self.actionPlay)
        self.menuPlayback.addAction(self.actionPause)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionNext)
        self.menuPlayback.addAction(self.actionPrevious)
        self.menu.addAction(self.actionAbout_MellowPlayer)
        self.menu.addSeparator()
        self.menu.addAction(self.actionReport_a_bug)
        self.menubar.addAction(self.menuApplication.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Mellow Player"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Welcome to Mellow Player!</span></p><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">No streaming service is loaded.</span></p></body></html>"))
        self.pushButtonPreferences.setText(_translate("MainWindow", "Preferences"))
        self.pushButtonLoad.setText(_translate("MainWindow", "Load service"))
        self.pushButtonQuit.setText(_translate("MainWindow", "Quit"))
        self.menuApplication.setTitle(_translate("MainWindow", "Application"))
        self.menuPlayback.setTitle(_translate("MainWindow", "Control"))
        self.menu.setTitle(_translate("MainWindow", "Help"))
        self.actionChoose_service.setText(_translate("MainWindow", "Choose service"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionNext.setText(_translate("MainWindow", "Next"))
        self.actionPrevious.setText(_translate("MainWindow", "Previous"))
        self.actionAbout_MellowPlayer.setText(_translate("MainWindow", "About Mellow Player"))
        self.actionReport_a_bug.setText(_translate("MainWindow", "Report a bug"))

from mellowplayer.gui.web import WebView
from . import icons_rc
