# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/colin/Desktop/MellowPlayer/forms/main_window.ui'
#
# Created: Tue Oct 28 22:31:11 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(821, 633)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/MellowPlayer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageHome = QtGui.QWidget()
        self.pageHome.setObjectName(_fromUtf8("pageHome"))
        self.gridLayout_2 = QtGui.QGridLayout(self.pageHome)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 10, 1, 1, 1)
        self.label = QtGui.QLabel(self.pageHome)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 6, 2, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 1, 0, 1, 1)
        self.pushButtonPreferences = QtGui.QPushButton(self.pageHome)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPreferences.sizePolicy().hasHeightForWidth())
        self.pushButtonPreferences.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/preferences-system.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonPreferences.setIcon(icon1)
        self.pushButtonPreferences.setObjectName(_fromUtf8("pushButtonPreferences"))
        self.gridLayout_3.addWidget(self.pushButtonPreferences, 1, 1, 1, 1)
        self.pushButtonQuit = QtGui.QPushButton(self.pageHome)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQuit.sizePolicy().hasHeightForWidth())
        self.pushButtonQuit.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("exit"))
        self.pushButtonQuit.setIcon(icon)
        self.pushButtonQuit.setObjectName(_fromUtf8("pushButtonQuit"))
        self.gridLayout_3.addWidget(self.pushButtonQuit, 2, 1, 1, 1)
        self.pushButtonSelect = QtGui.QPushButton(self.pageHome)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSelect.sizePolicy().hasHeightForWidth())
        self.pushButtonSelect.setSizePolicy(sizePolicy)
        self.pushButtonSelect.setIcon(icon)
        self.pushButtonSelect.setObjectName(_fromUtf8("pushButtonSelect"))
        self.gridLayout_3.addWidget(self.pushButtonSelect, 0, 1, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageHome)
        self.pageWeb = QtGui.QWidget()
        self.pageWeb.setObjectName(_fromUtf8("pageWeb"))
        self.gridLayout_4 = QtGui.QGridLayout(self.pageWeb)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.webView = WebView(self.pageWeb)
        self.webView.setObjectName(_fromUtf8("webView"))
        self.gridLayout_4.addWidget(self.webView, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageWeb)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 821, 34))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuApplication = QtGui.QMenu(self.menubar)
        self.menuApplication.setObjectName(_fromUtf8("menuApplication"))
        self.menuPlayback = QtGui.QMenu(self.menubar)
        self.menuPlayback.setObjectName(_fromUtf8("menuPlayback"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSelect_service = QtGui.QAction(MainWindow)
        self.actionSelect_service.setIcon(icon)
        self.actionSelect_service.setObjectName(_fromUtf8("actionSelect_service"))
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setIcon(icon1)
        self.actionPreferences.setObjectName(_fromUtf8("actionPreferences"))
        self.actionPlayPause = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/media-playback-start.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlayPause.setIcon(icon2)
        self.actionPlayPause.setObjectName(_fromUtf8("actionPlayPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/media-playback-stop.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/media-playback-pause.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon4)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionNext = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/media-seek-forward.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext.setIcon(icon5)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionPrevious = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/media-seek-backward.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious.setIcon(icon6)
        self.actionPrevious.setObjectName(_fromUtf8("actionPrevious"))
        self.actionAbout_MellowPlayer = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/help-about.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout_MellowPlayer.setIcon(icon7)
        self.actionAbout_MellowPlayer.setObjectName(_fromUtf8("actionAbout_MellowPlayer"))
        self.actionReport_a_bug = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/tools-report-bug.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionReport_a_bug.setIcon(icon8)
        self.actionReport_a_bug.setObjectName(_fromUtf8("actionReport_a_bug"))
        self.actionQuit = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/application-exit.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon9)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuApplication.addAction(self.actionSelect_service)
        self.menuApplication.addAction(self.actionPreferences)
        self.menuApplication.addSeparator()
        self.menuApplication.addAction(self.actionQuit)
        self.menuPlayback.addAction(self.actionPlayPause)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addAction(self.actionNext)
        self.menuPlayback.addAction(self.actionPrevious)
        self.menu.addAction(self.actionAbout_MellowPlayer)
        self.menu.addSeparator()
        self.menu.addAction(self.actionReport_a_bug)
        self.menubar.addAction(self.menuApplication.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Mellow Player", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><img src=\":/MellowPlayer.png\"/></p><p align=\"center\"><span style=\" font-size:18pt; font-weight:600;\">Welcome to Mellow Player!</span></p><p align=\"center\"><span style=\" font-size:14pt; font-style:italic;\">No streaming service is selected.</span></p><p align=\"center\"><br/></p></body></html>", None))
        self.pushButtonPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.pushButtonQuit.setText(_translate("MainWindow", "Quit", None))
        self.pushButtonSelect.setText(_translate("MainWindow", "Select service", None))
        self.menuApplication.setTitle(_translate("MainWindow", "Application", None))
        self.menuPlayback.setTitle(_translate("MainWindow", "Control", None))
        self.menu.setTitle(_translate("MainWindow", "Help", None))
        self.actionSelect_service.setText(_translate("MainWindow", "Select service", None))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences", None))
        self.actionPlayPause.setText(_translate("MainWindow", "Play/Pause", None))
        self.actionPlayPause.setShortcut(_translate("MainWindow", "Media Play", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionStop.setShortcut(_translate("MainWindow", "Media Stop", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionPause.setShortcut(_translate("MainWindow", "Media Play", None))
        self.actionNext.setText(_translate("MainWindow", "Next", None))
        self.actionNext.setShortcut(_translate("MainWindow", "Media Next", None))
        self.actionPrevious.setText(_translate("MainWindow", "Previous", None))
        self.actionPrevious.setShortcut(_translate("MainWindow", "Media Previous", None))
        self.actionAbout_MellowPlayer.setText(_translate("MainWindow", "About Mellow Player", None))
        self.actionReport_a_bug.setText(_translate("MainWindow", "Report a bug", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

from mellowplayer.gui.web import WebView
from . import icons_rc
